name: nBack
options:
  bundleIdPrefix: io.lanza
targets:
  nBack:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Source]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
